### ISSUE TITLE
Integration of uv locally

### ISSUE THREAD

**Issue by picsalex** [picselliahq/picsellia-training-engine#103]
**As a Data Scientist**
**I want to add a requirements.txt handled by uv**
**So that it's easier to manage data science dependencies**

**Acceptance Criteria:**
- [x] UV runs successfully on a Data Scientist laptop
- [x] The process is documented inside the Readme

**Definition of Done:**
- [x] All acceptance criteria are met.
- [x] Documentation is updated.

**Comment by SoniaGrh** [comment]
@picsalex changes done, waiting for you review
