### ISSUE TITLE
Log recall by class on Yolo models

### ISSUE THREAD

**Issue by PN-picsell** [picselliahq/picsellia-training-engine#13]
![Image](https://user-images.githubusercontent.com/110984677/226483623-68d6832e-b68e-4d7e-8416-264ce1f4e843.png)

**Comment by picsalex** [comment]
@PN-picsell est ce que c'est toujours d'actualité ? Notamment par rapport la liste de métriques qu'on avait défini ici: https://www.notion.so/picsellia/Choose-which-metrics-should-be-displayed-for-each-experiment-98-7e381c91b9b64213a0ad8cfe0ea00c87

**Comment by PN-picsell** [comment]
Ca peut être pas mal de le mettre dans la roadmap oui, sachant que pour l'instant on a fait qu'un agrégat des metriques que les différents models nous proposent mais ça peut etre bien de rajouter des choses qui nous paraissent pertinentes
Peut etre clore ce ticket et en faire un nouveau pour correspondre a vos sprints
