### ISSUE TITLE
Create a RTE Project Repo and add the scripts

### ISSUE THREAD

**Issue by picsalex** [picselliahq/picsellia-training-engine#133]
**As a DS**
**I want to create a dedicated RTE's scripts repo**
**So that collaboration becomes easier**

**Acceptance Criteria:**
- [x] A repo exists
- The following scripts are imported:
   - [x] Import annotations with geoformat
   - [x] Clustering script
   - [x] 2017 RTE scripts
 - [x] Add a `pre-commit` file
 - [x] Add a README
 - [x] Push RTE 2017 script

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] Code is reviewed and approved.
- [x] Documentation is updated.

**Comment by SoniaGrh** [comment]
[Github Repository](https://github.com/picselliahq/picsellia-RTE)
