### ISSUE TITLE
Integrate a new polygonal instance segmentation model

### ISSUE THREAD

**Issue by picsalex** [picselliahq/picsellia-training-engine#135]
**As a DS**
**I want to integrate a new segmentation model**
**So that cables can be segmented for the RTE project**

**Acceptance Criteria:**
- [x] R&D is made to find the model to integrate

**Definition of Done:**
- [x] All acceptance criteria are met.

**Comment by SoniaGrh** [comment]
[Notion documentation](https://www.notion.so/picsellia/Integrate-a-new-polygonal-instance-segmentation-model-135-014da21d6bc54ab0b7b0c3313f8ad53c)
