### ISSUE TITLE
Prepare the steps list

### ISSUE THREAD

**Issue by picsalex** [picselliahq/picsellia-training-engine#93]
**As a DataScientist**
**I want to prepare the step list**
**So that I understand which steps will have to be coded and how**

**Acceptance Criteria:**
A documentation which lists all the steps with:

   - Input/Output
   - Name
   - Order

The steps' categories to cover are:

- [x] Context Preparation
- [x] Data Extraction
- [x] Data Validation
- [x] Data Preparation
- [x] Model Loading
- [x] Model Training
- [x] Model Convertor
- [x] Model Exporter
- [x] Model Inference
- [x] Model Evaluation
- [x] Model Validation
- [x] Callback preparator
- [x] Data Augmentation preparator
- [x] A DAG has been drawned
- [x] Model Extraction
- [x] Model Validation
- [x] Model Preparation
- [x] Hyperparam validation

Other requirements:

- [x] The list has been validated by @PN-picsell

**Comment by SoniaGrh** [comment]
[Notion link](https://www.notion.so/picsellia/Prepare-the-steps-list-list-input-output-what-it-does-93-2d2c713f46fd43999573c5f0d38c5cf0)

**Comment by picsalex** [comment]
Sonia is applying PN-Picsell feedback

**Comment by picsalex** [comment]
Need a call with @n7-Thomas or Hicham to validate the hyperparam system

**Comment by picsalex** [comment]
Sonia you can read the relevant [Notion's section update](https://www.notion.so/picsellia/Prepare-the-steps-list-list-input-output-what-it-does-93-2d2c713f46fd43999573c5f0d38c5cf0?pvs=4#c3778072e8ba4dc78427aa95797423c4)
